
name: test-check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Ставим зависимости
      - run: npm install
      - run: npm  version
      - run: make lint
      - name: run tests
        run: npm test # name и run относятся к одной задаче, поэтому дефис ставится только перед name
        